Discrete Gradient : the $D$ operator
===========================

## 1. Definition of the $D$ (Discrete Gradient) operator

The $D$ is defined as a **linear** operator, which maps an image to another image whose values are pairs of **vertical and horizontal finite differences**:

$(Dx)_{n_1,n_2} = ( (Dx)_{n_1,n_2,v}, (Dx)_{n_1,n_2,h}) = (x_{n_1+1,n_2} - x_{n_1,n_2} , x_{n_1,n_2+1} - x_{n_1,n_2}) \in \R^2$

where :
- $n_1$ is the row number,
- $n_2$ is the column number,
- $n_1 = n_2 = 0$ corresponds to the pixel at the top left corner
- Neumann boundary conditions are assumed : **a difference accross the boundary is zero**

The operator $D$, as a function, can be defined as :



In [2]:
import numpy as np
def D(x):
    vdiff = np.r_[np.diff(x,1,0), np.zeros([1,x.shape[1]])] 
    hdiff = np.c_[np.diff(x,1,1), np.zeros([x.shape[0],1])] 
    return np.concatenate((vdiff[...,np.newaxis], hdiff[...,np.newaxis]), axis=2) 

Explanations :
- **np.diff(x,i,n)** computes the $(i)$-th order differences along the $n$-th axis. In the case of $D$ we have the first order difference, which yields out[i] = x[i+1] - x[i] along the given axis.

In [25]:
x = np.array([[1, 2, 4, 7, 0],[1,8,7,9,6],[0, 3, 8, 9, 0],[4,7,7,7,7]])
print('x:',x)

x: [[1 2 4 7 0]
 [1 8 7 9 6]
 [0 3 8 9 0]
 [4 7 7 7 7]]


In [31]:
print('np.diff(x,1,0), vertical differences:\n',np.diff(x,1,0),'\n')
print('np.diff(x,1,1), horizontal differences:\n',np.diff(x,1,1))

np.diff(x,1,0), vertical differences:
 [[ 0  6  3  2  6]
 [-1 -5  1  0 -6]
 [ 4  4 -1 -2  7]] 

np.diff(x,1,1), horizontal differences:
 [[ 1  2  3 -7]
 [ 7 -1  2 -3]
 [ 3  5  1 -9]
 [ 3  0  0  0]]


- **np.zeros([a,b])** creates a vector of zeros. For *vdiff* we create a row vector of zeros with the same number of columns as $x$, for *hdiff*, we create a column vector of zeros with the same number of rows as $x$.

- **np.r_[x,y]** concatenates $x$ and $y$ along the **0th/row** axis

In [3]:
np.r_[[1,2,3], [4,5,6]]

array([1, 2, 3, 4, 5, 6])


 ==> The np.zeros arrays are created and concatenated with the **np.diff** to ensure that the last row/or column has $0$-s for the Neumann boundary conditions. Example :

In [34]:
print(np.r_[np.diff(x,1,0), np.zeros([1,x.shape[1]])])

[[ 0.  6.  3.  2.  6.]
 [-1. -5.  1.  0. -6.]
 [ 4.  4. -1. -2.  7.]
 [ 0.  0.  0.  0.  0.]]


Therefore, 
- $ (Dx)_{n_1,n_2,v} = x_{n_1+1,n_2}-x_{n_1,n_2}$ is computed by the *vdiff* line (for each pixel of the original image),
- $ (Dx)_{n_1,n_2,h} = x_{n_1,n_2+1}-x_{n_1,n_2}$ is computed by the *hdiff* line (for each pixel of the original image).

What's left to do is to concatenate them so that for each pixel of the original image, we produce a $ ((Dx)_{n_1,n_2,v},(Dx)_{n_1,n_2,h})\in \R^2$.

The **return** therefore concatenates both of *vdiff* and *hdiff* along a new third dimension. This produces a matrix where each element is an array $(Dx)_{n_1,n_2} \in \R^2$, i.e for each pixel of the original image.
- *np.newaxis* specifies that we want to add a new dimension to *vdiff* and *hdiff*, and we then concatenate both on this new dim. using the *axis=2* parameter 



In [41]:
vdiff = np.r_[np.diff(x,1,0), np.zeros([1,x.shape[1]])]
hdiff = np.c_[np.diff(x,1,1), np.zeros([x.shape[0],1])]

print('vdiff, vertical differences:\n',vdiff,'\n')
print('hdiff, horizontal differences:\n',hdiff,'\n')
print('total Dx:',np.concatenate((vdiff[...,np.newaxis], hdiff[...,np.newaxis]), axis=2))

vdiff, vertical differences:
 [[ 0.  6.  3.  2.  6.]
 [-1. -5.  1.  0. -6.]
 [ 4.  4. -1. -2.  7.]
 [ 0.  0.  0.  0.  0.]] 

hdiff, horizontal differences:
 [[ 1.  2.  3. -7.  0.]
 [ 7. -1.  2. -3.  0.]
 [ 3.  5.  1. -9.  0.]
 [ 3.  0.  0.  0.  0.]] 

total Dx: [[[ 0.  1.]
  [ 6.  2.]
  [ 3.  3.]
  [ 2. -7.]
  [ 6.  0.]]

 [[-1.  7.]
  [-5. -1.]
  [ 1.  2.]
  [ 0. -3.]
  [-6.  0.]]

 [[ 4.  3.]
  [ 4.  5.]
  [-1.  1.]
  [-2. -9.]
  [ 7.  0.]]

 [[ 0.  3.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]]


The 

In [42]:
D = lambda x : np.c_['2,3',np.r_[np.diff(x,1,0), np.zeros([1,x.shape[1]])],np.c_[np.diff(x,1,1), np.zeros([x.shape[0],1])]]

defined in *ForwardBackwardDual.ipynb* is just a more compact definition of D(x).