Discrete Gradient : the $D$ operator
===========================

## 1. Definition of the $D$ (Discrete Gradient) operator

The $D$ is defined as a **linear** operator, which maps an image to another image whose values are pairs of **vertical and horizontal finite differences**:

$(Dx)_{n_1,n_2} = ( (Dx)_{n_1,n_2,v}, (Dx)_{n_1,n_2,h}) = (x_{n_1+1,n_2} - x_{n_1,n_2} , x_{n_1,n_2+1} - x_{n_1,n_2}) \in \R^2$

where :
- $n_1$ is the row number,
- $n_2$ is the column number,
- $n_1 = n_2 = 0$ corresponds to the pixel at the top left corner
- Neumann boundary conditions are assumed : **a difference accross the boundary is zero**

The operator $D$, as a function, can be defined as :



In [1]:
import numpy as np
def D(x):
    vdiff = np.r_[np.diff(x,1,0), np.zeros([1,x.shape[1]])] 
    hdiff = np.c_[np.diff(x,1,1), np.zeros([x.shape[0],1])] 
    return np.concatenate((vdiff[...,np.newaxis], hdiff[...,np.newaxis]), axis=2) 

Explanations :
- **np.diff(x,i,n)** computes the $(i)$-th order differences along the $n$-th axis. In the case of $D$ we have the first order difference, which yields out[i] = x[i+1] - x[i] along the given axis.

In [2]:
x = np.array([[1, 2, 4, 7, 0],[1,8,7,9,6],[0, 3, 8, 9, 0],[4,7,7,7,7],[0,1,2,3,4]])
print('x:',x)

x: [[1 2 4 7 0]
 [1 8 7 9 6]
 [0 3 8 9 0]
 [4 7 7 7 7]
 [0 1 2 3 4]]


In [3]:
print('np.diff(x,1,0), vertical differences:\n',np.diff(x,1,0),'\n')
print('np.diff(x,1,1), horizontal differences:\n',np.diff(x,1,1))

np.diff(x,1,0), vertical differences:
 [[ 0  6  3  2  6]
 [-1 -5  1  0 -6]
 [ 4  4 -1 -2  7]
 [-4 -6 -5 -4 -3]] 

np.diff(x,1,1), horizontal differences:
 [[ 1  2  3 -7]
 [ 7 -1  2 -3]
 [ 3  5  1 -9]
 [ 3  0  0  0]
 [ 1  1  1  1]]


- **np.zeros([a,b])** creates a vector of zeros. For *vdiff* we create a row vector of zeros with the same number of columns as $x$, for *hdiff*, we create a column vector of zeros with the same number of rows as $x$.

- **np.r_[x,y]** concatenates $x$ and $y$ along the **0th/row** axis

In [4]:
np.r_[[1,2,3], [4,5,6]]

array([1, 2, 3, 4, 5, 6])


 ==> The np.zeros arrays are created and concatenated with the **np.diff** to ensure that the last row/or column has $0$-s for the Neumann boundary conditions. Example :

In [5]:
print(np.r_[np.diff(x,1,0), np.zeros([1,x.shape[1]])])

[[ 0.  6.  3.  2.  6.]
 [-1. -5.  1.  0. -6.]
 [ 4.  4. -1. -2.  7.]
 [-4. -6. -5. -4. -3.]
 [ 0.  0.  0.  0.  0.]]


Therefore, 
- $ (Dx)_{n_1,n_2,v} = x_{n_1+1,n_2}-x_{n_1,n_2}$ is computed by the *vdiff* line (for each pixel of the original image),
- $ (Dx)_{n_1,n_2,h} = x_{n_1,n_2+1}-x_{n_1,n_2}$ is computed by the *hdiff* line (for each pixel of the original image).

What's left to do is to concatenate them so that for each pixel of the original image, we produce a $ ((Dx)_{n_1,n_2,v},(Dx)_{n_1,n_2,h})\in \R^2$.

The **return** therefore concatenates both of *vdiff* and *hdiff* along a new third dimension. This produces a matrix where each element is an array $(Dx)_{n_1,n_2} \in \R^2$, i.e for each pixel of the original image.
- *np.newaxis* specifies that we want to add a new dimension to *vdiff* and *hdiff*, and we then concatenate both on this new dim. using the *axis=2* parameter 



In [6]:
vdiff = np.r_[np.diff(x,1,0), np.zeros([1,x.shape[1]])]
hdiff = np.c_[np.diff(x,1,1), np.zeros([x.shape[0],1])]

print('vdiff, vertical differences:\n',vdiff,'\n')
print('hdiff, horizontal differences:\n',hdiff,'\n')
dx = np.concatenate((vdiff[...,np.newaxis], hdiff[...,np.newaxis]), axis=2)
print('total Dx:',dx)

vdiff, vertical differences:
 [[ 0.  6.  3.  2.  6.]
 [-1. -5.  1.  0. -6.]
 [ 4.  4. -1. -2.  7.]
 [-4. -6. -5. -4. -3.]
 [ 0.  0.  0.  0.  0.]] 

hdiff, horizontal differences:
 [[ 1.  2.  3. -7.  0.]
 [ 7. -1.  2. -3.  0.]
 [ 3.  5.  1. -9.  0.]
 [ 3.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  0.]] 

total Dx: [[[ 0.  1.]
  [ 6.  2.]
  [ 3.  3.]
  [ 2. -7.]
  [ 6.  0.]]

 [[-1.  7.]
  [-5. -1.]
  [ 1.  2.]
  [ 0. -3.]
  [-6.  0.]]

 [[ 4.  3.]
  [ 4.  5.]
  [-1.  1.]
  [-2. -9.]
  [ 7.  0.]]

 [[-4.  3.]
  [-6.  0.]
  [-5.  0.]
  [-4.  0.]
  [-3.  0.]]

 [[ 0.  1.]
  [ 0.  1.]
  [ 0.  1.]
  [ 0.  1.]
  [ 0.  0.]]]


The 

In [7]:
D = lambda x : np.c_['2,3',np.r_[np.diff(x,1,0), np.zeros([1,x.shape[1]])],np.c_[np.diff(x,1,1), np.zeros([x.shape[0],1])]]

defined in *ForwardBackwardDual.ipynb* is just a more compact definition of D(x).

## 2. The corresponding $D$* Hermitian adjoint of $D$

In *ForwardBackwardDual.ipynb*,  $D^*$ is mentioned as being the adjoint of $D$. It's therefore defined such that, for any $x$ and $y$ :

$$ \langle D(x) , y \rangle  =  \langle x , D^*(y) \rangle$$

As we're operating here in finite dimensions, i.e our operators such as $D$ can be represented as matrices, **This adjoint/hermitian adjoint is given by the conjugate transpose**. The conjugate transpose of a $m \times n$ matrix $A$ is formally defined by 

$$ (A^H)_{ij} = \overline{A_{ji}}$$

==> For real matrices, the conjugate transpose should just be the transpose, i.e $A^H = A^T$

In our case however and with how they decide to define $D$, we don't have a $D$ matrix, but rather a function that is applied to $x$, s.t $D(x)$.


$D^*$ as a function will therefore perform similar operations than $D$ but such that applying it to the $D(x)$ maps back the discrete gradient to an image (?). The formula *ForwardBackwardDual.ipynb* gives us for $D^*$ is :

In [9]:
Dadj = lambda v : np.r_['0,2',-v[0,:,0],-np.diff(v[:-1,:,0],1,0),v[-2,:,0]] + np.c_['1,2',-v[:,0,1],-np.diff(v[:,:-1,1],1,1),v[:,-2,1]]

By expanding it a bit to make it more readable, we can write 

In [10]:
def Dadj(v):

    top_boundary = -v[0, :, 0]
    interior_vertical_differences = -np.diff(v[:-1, :, 0], 1, 0)
    bottom_boundary = v[-2, :, 0]
    
    left_boundary = -v[:, 0, 1]
    interior_horizontal_differences = -np.diff(v[:, :-1, 1], 1, 1)
    right_boundary = v[:, -2, 1]
    
    concat_axis_0 = np.r_['0,2',
                          top_boundary,
                          interior_vertical_differences,
                          bottom_boundary]
    
    concat_axis_1 = np.c_['1,2',
                          left_boundary,
                          interior_horizontal_differences,
                          right_boundary]

    return concat_axis_0 + concat_axis_1

**Explanations** :

- **-v[0,:,0]** takes the first column in the first element of *v* and negates it (uses it as a left-boundary for the Neumann conditions)
- **v[-2,:,0]** takes the first column of the second-to-last element of *v* (used as the right-boundary for the Neumann conditions)
- **-np.diff(v[:-1,:,0],1,0)** Takes the first column of all the elements in *v* but the last one to use them as rows, and then compute the **vertical** differences between them. Then negates it. ==> Interior portion of the vertical differences.

    Examples (knowing that we use $D(x)$ as $v$ in what follows) :

In [11]:
print('Reminder of D(x) :\n', dx)

Reminder of D(x) :
 [[[ 0.  1.]
  [ 6.  2.]
  [ 3.  3.]
  [ 2. -7.]
  [ 6.  0.]]

 [[-1.  7.]
  [-5. -1.]
  [ 1.  2.]
  [ 0. -3.]
  [-6.  0.]]

 [[ 4.  3.]
  [ 4.  5.]
  [-1.  1.]
  [-2. -9.]
  [ 7.  0.]]

 [[-4.  3.]
  [-6.  0.]
  [-5.  0.]
  [-4.  0.]
  [-3.  0.]]

 [[ 0.  1.]
  [ 0.  1.]
  [ 0.  1.]
  [ 0.  1.]
  [ 0.  0.]]]


In [12]:
print('We then have :\n')
print('v[0,:,0] :', dx[0,:,0], '\n')
print('v[-2,:,0] :', dx[-2,:,0], '\n')
print('v[:-1,:,0] : \n',dx[:-1,:,0], '\n')
print('np.diff(dx[:-1,:,0],1,0) : \n',np.diff(dx[:-1,:,0],1,0))

We then have :

v[0,:,0] : [0. 6. 3. 2. 6.] 

v[-2,:,0] : [-4. -6. -5. -4. -3.] 

v[:-1,:,0] : 
 [[ 0.  6.  3.  2.  6.]
 [-1. -5.  1.  0. -6.]
 [ 4.  4. -1. -2.  7.]
 [-4. -6. -5. -4. -3.]] 

np.diff(dx[:-1,:,0],1,0) : 
 [[ -1. -11.  -2.  -2. -12.]
 [  5.   9.  -2.  -2.  13.]
 [ -8. -10.  -4.  -2. -10.]]


Then, in the same manner, we have :

- **-v[:,0,1]** : Extracts the first "value" of the second channel of each sub-element *v*, negates it ==> used as the 'left'-boundary
- **-np.diff(v[:,:-1,1],1,1)** : Takes the second channel of all *v* elements, then computes the differences along the axis 1 (i.e columns), excluding the very last one. ==> Interior portion of the horizontal differences
- **v[:,-2,1]** : The second-to-last column of the second channel of *v*, and added as the 'right' boundary.

In [13]:
print('We have :\n')
print('v[:,0,1] :', dx[:,0,1], '\n')
print('v[:,-2,1] :', dx[:,-2,1], '\n')
print('v[:,:,-1,1] : \n', dx[:,:-1,1], '\n')
print('np.diff(dx[:,:,-1,1],1,1) : \n',np.diff(dx[:,:-1,1],1,1))

We have :

v[:,0,1] : [1. 7. 3. 3. 1.] 

v[:,-2,1] : [-7. -3. -9.  0.  1.] 

v[:,:,-1,1] : 
 [[ 1.  2.  3. -7.]
 [ 7. -1.  2. -3.]
 [ 3.  5.  1. -9.]
 [ 3.  0.  0.  0.]
 [ 1.  1.  1.  1.]] 

np.diff(dx[:,:,-1,1],1,1) : 
 [[  1.   1. -10.]
 [ -8.   3.  -5.]
 [  2.  -4. -10.]
 [ -3.   0.   0.]
 [  0.   0.   0.]]


After computing these quantities, we have two separate concatenations :

- **np.r_['0,2', ...]** Will take the top-boundary, the interior vertical differences and the bottom boundary and concatenate them along the first axis (i.e stacking them on each other)

- **np.c_['1,2', ...]** Will take the left-boundary, the interior horizontal differences and the right-boundary and concatenate them along the second axis (i.e next to each other)

In [14]:
np.r_['0,2',-dx[0,:,0],-np.diff(dx[:-1,:,0],1,0),dx[-2,:,0]]

array([[ -0.,  -6.,  -3.,  -2.,  -6.],
       [  1.,  11.,   2.,   2.,  12.],
       [ -5.,  -9.,   2.,   2., -13.],
       [  8.,  10.,   4.,   2.,  10.],
       [ -4.,  -6.,  -5.,  -4.,  -3.]])

In [15]:
np.c_['1,2',-dx[:,0,1],-np.diff(dx[:,:-1,1],1,1),dx[:,-2,1]]

array([[-1., -1., -1., 10., -7.],
       [-7.,  8., -3.,  5., -3.],
       [-3., -2.,  4., 10., -9.],
       [-3.,  3., -0., -0.,  0.],
       [-1., -0., -0., -0.,  1.]])

Finally, these two concatenated arrays are added **element-wise** to each other to yield a final 2D array that has the same shape as the original image $x$.

In [16]:
print(Dadj(dx))

[[ -1.  -7.  -4.   8. -13.]
 [ -6.  19.  -1.   7.   9.]
 [ -8. -11.   6.  12. -22.]
 [  5.  13.   4.   2.  10.]
 [ -5.  -6.  -5.  -4.  -2.]]


-------------
So basically, we have operations that revert the 3D array obtained from applying $D$ to $x$ back to a 2D-array (i.e image in our case). But we can see that 
$$D^*(D(x)) \neq x $$